configuration:
  runtime: concord-v2
  dependencies:
    - "mvn://org.benbroadaway.unifi:unifi-concord-task:0.0.4"

profiles:
  state_on:
    configuration:
      arguments:
        relayState: true

  state_off:
    configuration:
      arguments:
        relayState: false

triggers:
  - manual:
      name: Disable Plug
      entryPoint: default
      arguments:
        relayState: false

  - manual:
      name: Enable Plug
      entryPoint: default
      arguments:
        relayState: true

  - cron:  # disable plug
      spec: "0 22 * * *"
      timezone: "America/Chicago"
      entryPoint: default
      arguments:
        relayState: false

  - cron:  # enable plug
      spec: "20 6 * * *"
      timezone: "America/Chicago"
      entryPoint: default
      arguments:
        relayState: true

flows:
  default:
    - set:
        unifiCreds: "${crypto.exportCredentials('unifi', 'unifi-ben', null)}"
    # unifiHost and uspName parameters provided by project configuration arguments
    - task: unifi
      in:
        action: setUspState
        username: "${unifiCreds.username}"
        password: "${unifiCreds.password}"
        relayState: "${relayState}"
