configuration:
  runtime: concord-v2
  dependencies:
    - mvn://org.apache.groovy:groovy-all:pom:4.0.13

profiles:
  state_on:
    configuration:
      arguments:
        relayState: true

  state_off:
    configuration:
      arguments:
        relayState: false

triggers:
  - manual:
      name: Disable Plug
      entryPoint: default
      arguments:
        relayState: false

  - manual:
      name: Enable Plug
      entryPoint: default
      arguments:
        relayState: true

  - cron:  # disable plug
      spec: "0 22 * * *"
      timezone: "America/Chicago"
      entryPoint: default
      arguments:
        relayState: false

  - cron:  # enable plug
      spec: "20 6 * * *"
      timezone: "America/Chicago"
      entryPoint: default
      arguments:
        relayState: true

flows:
  default:
    - set:
        unifiCreds: "${crypto.exportCredentials('unifi', 'unifi-ben', null)}"
        # This MUST be customized (or overridden from other settings)
        plugName: "${orDefault('plugName', 'My-USP-Plug')}"
    - name: "Run USPToggle script (relayState == ${relayState})"
      script: src/main/groovy/pkg/USPToggle.groovy
